### ISSUE TITLE
Issue with Python script

### ISSUE THREAD

**Issue by iamsamsaul** [CiscoSecurity/amp-04-find-duplicate-guids#2]
Hi there,

First of all, thanks for your efforts by writing this script.

When I'm running the Python script, I'm getting the following error:

py find_duplicate_guids.py
Traceback (most recent call last):
File "find_duplicate_guids.py", line 147, in <module>
main()
File "find_duplicate_guids.py", line 124, in main
total_guids = response_json['metadata']['results']['total']
KeyError: 'metadata'

 Any help will be highly appreciated.

Regards,

Sam

**Comment by smalluk** [comment]
Hi Sam,

#I have gotten the same error - did you happen to find out what the issue was?

EDIT: Resolved - had to change the API URL to have eu in it as I am in the eu cloud!

Thanks,
Daniel.
